apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickwit
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: { app: quickwit }
  template:
    metadata:
      labels: { app: quickwit }
    spec:
      containers:
        - name: quickwit
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          args: [run, --config, /etc/quickwit/quickwit.yaml]
          env:
            - name: QW_ENABLED_SERVICES
              value: control_plane,metastore,indexer,janitor,searcher
            - name: QW_LISTEN_ADDRESS
              value: 0.0.0.0
          ports:
            - { containerPort: 7280, name: rest }
            - { containerPort: 7281, name: grpc }
            - { containerPort: 4317, name: otlp-grpc }
            - { containerPort: 4318, name: otlp-http }
          volumeMounts:
            - { name: config, mountPath: /etc/quickwit }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap: { name: quickwit-config }
