apiVersion: v1
kind: Service
metadata:
  name: quickwit
spec:
  selector: { app: quickwit }
  ports:
    - { port: 7280, name: rest }
    - { port: 7281, name: grpc }
    - { port: 4317, name: otlp-grpc }
    - { port: 4318, name: otlp-http }
