[package]
name = "lakewing"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lance = { workspace = true }
lance-io = { workspace = true }
lance-index = { workspace = true }
lance-file = { workspace = true }
lance-namespace = { workspace = true }
lance-namespace-impls = { workspace = true }
object_store = { workspace = true }
arrow = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
poem = { workspace = true }
duckdb = { workspace = true }
foyer = { workspace = true }
bytes = { workspace = true }
anyhow = { workspace = true }
flate2 = { workspace = true }
rustix = { workspace = true }
parquet = { workspace = true }
geoarrow-array = { workspace = true }
tonic = { workspace = true }
tokio-stream = { workspace = true }
arrow-flight = { workspace = true }
geoarrow-schema = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
tracing-opentelemetry = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
